package:
  name: wordcloud
  version: "1.3.1"
  
source:
  git_url: https://github.com/amueller/word_cloud.git
  
requirements:
  build:
    - python
    - matplotlib
    - numpy >=1.6.1
    - pillow

  run:
    - python
    - matplotlib
    - numpy >=1.6.1
    - pillow


test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli.py --help

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
